### ISSUE TITLE
python main.py   --sel paws_train   --fname configs/paws/cifar10_train.yaml     error

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/suncet#15]
INFO:root:making cifar10 data transforms
INFO:root:keep file: cifar10_subsets/spc.4000_split.152.txt
_make_multicrop_cifar10_transforms distortion strength 0.5
INFO:root:copying data locally
INFO:root:No job-id, will load directly from network file
INFO:root:data-path datasets/cifar10-data/
INFO:root:copying data locally
INFO:root:No job-id, will load directly from network file
INFO:root:data-path datasets/cifar10-data/
INFO:root:Using cifar10_subsets/spc.4000_split.152.txt
INFO:root:num-labeled 4000
INFO:root:num-labeled target 0 400
INFO:root:num-labeled target 1 400
INFO:root:num-labeled target 2 400
INFO:root:num-labeled target 3 400
INFO:root:num-labeled target 4 400
INFO:root:num-labeled target 5 400
INFO:root:num-labeled target 6 400
INFO:root:num-labeled target 7 400
INFO:root:num-labeled target 8 400
INFO:root:num-labeled target 9 400
INFO:root:min. labeled indices 400
INFO:root:iterations per epoch: 195
INFO:root:Epoch 1
Traceback (most recent call last):
  File "/home/chenxin/disk1/github/suncet/main.py", line 90, in <module>
    mp.spawn(
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/chenxin/disk1/github/suncet/main.py", line 77, in process_main
    return paws(params)
  File "/home/chenxin/disk1/github/suncet/src/paws_train.py", line 265, in main
    for itr, udata in enumerate(unsupervised_loader):
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/chenxin/disk1/anaconda3/envs/suncet/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object '_make_cifar10_transforms.<locals>.get_color_distortion.<locals>.Solarize'

Process finished with exit code 1

**Comment by MidoAssran** [comment]
Hi @mathpopo 

Thanks for raising this issue! Should be fixed now if you pull the latest version of the repo.
